intensive_django/about/urls.py
from about import views
from django.urls import path

app_name = 'about'
urlpatterns = [
    path('', views.DescriptionView.as_view(), name='description'),
]

intensive_django/catalog/urls.py
from catalog.views import ItemDetailView, ItemListView
from django.urls import path, re_path

app_name = 'catalog'

urlpatterns = [
    path('', ItemListView.as_view(), name='item_list'),
    re_path(r'(?P<pk>[1-9][0-9]*)/$', ItemDetailView.as_view(),
            name='item_detail'),
]

intensive_django/feedback/urls.py
from django.urls import path
from feedback import views

app_name = 'feedback'
urlpatterns = [
    path('', views.FeedbackFormView.as_view(), name='feedback'),
]

intensive_django/homepage/urls.py
from django.urls import path
from homepage import views

app_name = 'homepage'
urlpatterns = [
    path('', views.HomepageView.as_view(), name='home'),
]

intensive_django/intensive_django/urls.py
import Core.views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('homepage.urls')),
    path('catalog/', include('catalog.urls')),
    path('about/', include('about.urls')),
    path('feedback/', include('feedback.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
]

handler404 = Core.views.NotFoundView.as_view()


if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

intensive_django/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path, reverse_lazy
from users.views import (ProfileView, SignUpFormView, UserDetailView,
                         UserListView)

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(
        template_name='users/login.html',
    ), name='login'),

    path('logout/', LogoutView.as_view(
        template_name='users/logout.html',
    ), name='logout'),

    path('password_change/', PasswordChangeView.as_view(
        template_name='users/password_change.html',
        success_url=reverse_lazy('users:password_change_done'),
    ), name='password_change'),

    path('password_change_done/', PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html',
    ), name='password_change_done'),

    path('password_reset/', PasswordResetView.as_view(
        template_name='users/password_reset.html',
        email_template_name='users/password_reset_email.html',
        success_url=reverse_lazy('users:password_reset_done'),
    ), name='password_reset'),

    path('password_reset_done/', PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html',
    ), name='password_reset_done'),

    path('password_reset_confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html',
             success_url=reverse_lazy('users:password_reset_complete'),
         ), name='password_reset_confirm'),

    path('password_reset_complete/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html',
    ), name='password_reset_complete'),

    path('signup/', SignUpFormView.as_view(), name='signup'),
    path('user_list/', UserListView.as_view(), name='user_list'),
    path(
        'user_detail/<int:pk>/',
        UserDetailView.as_view(),
        name='user_detail'
        ),
    path('profile/', ProfileView.as_view(), name='profile'),
]

intensive_django/templates/includes/footer.html
{% load static %}

<div class="container">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <p class="col-md-4 mb-0 text-muted">©
            <script>document.write(new Date().getFullYear())</script>
        </p>

        <a href="/"
           class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
            <img class="bi me-2" src="{% static 'favicon/favicon.ico' %}"
                 alt="pass">
        </a>

        <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
            <li>
                <a class="nav-link {% ifequal request.path '/' %} fw-bold {% endifequal %} link-dark "
                   href="{% url 'homepage:home' %}">Главная</a>
            </li>
            <li><a type="button"
                   class="nav-link {% ifequal request.path '/about/' %} fw-bold {% endifequal %} link-dark"
                   href="{% url 'about:description' %}">О нас</a>
            </li>
            <li><a type="button"
                   class="nav-link {% if '/catalog/' in request.path %} fw-bold {% endif %} link-dark"
                   href="{% url 'catalog:item_list' %}">Каталог</a>
            </li>
            <li><a type="button"
                   class="nav-link {% ifequal request.path '/feedback/' %} fw-bold {% endifequal %} link-dark"
                   href="{% url 'feedback:feedback' %}">Обратная связь</a>
            </li>
        </ul>
    </footer>
</div>

intensive_django/templates/includes/form.html
{% load crispy_forms_tags %}

<form method="{{ form_method }}">
    {% csrf_token %}

    {{ form|crispy }}

    <button class="btn btn-outline-primary" type="submit">
        {{ button_name }}
    </button>
</form>

intensive_django/templates/includes/header.html
{% load static %}
{% if birthday_users != None %}
<div class="alert alert-primary" role="alert">
  Сегодня день рождения у:
  {% for birthday_user in birthday_users %}
  <a href="{% url 'users:user_detail' pk=birthday_user.id %}">{% if birthday_user.first_name %} {{birthday_user.first_name}} - {% endif %}{{birthday_user.email}}</a>
    {%if not forloop.last%}
    , 
    {% endif %}
  {% endfor %}
</div>
{% endif %}
<div class="container">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
        <a href="/"
           class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
            <img class="bi me-2" src="{% static 'favicon/favicon.ico' %}"
                 alt="pass">
        </a>
        <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
            <li>
                <a class="nav-link {% ifequal request.path '/' %} fw-bold {% endifequal %} link-dark "
                   href="{% url 'homepage:home' %}">Главная</a>
            </li>
            <li><a type="button"
                   class="nav-link {% ifequal request.path '/about/' %} fw-bold {% endifequal %} link-dark"
                   href="{% url 'about:description' %}">О нас</a>
            </li>
            <li><a type="button"
                   class="nav-link {% if '/catalog/' in request.path %} fw-bold {% endif %} link-dark"
                   href="{% url 'catalog:item_list' %}">Каталог</a>
            </li>
            <li><a type="button"
                   class="nav-link {% ifequal request.path '/feedback/' %} fw-bold {% endifequal %} link-dark"
                   href="{% url 'feedback:feedback' %}">Обратная связь</a>
            </li>
            <li><a type="button"
                   class="nav-link {% ifequal request.path '/users/user_list/' %} fw-bold {% endifequal %} link-dark"
                   href="{% url 'users:user_list' %}">Список пользователей</a>
            </li>
            {% if user.is_authenticated %}
      <div class="dropdown">
        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          {% if context_user.first_name %}{{context_user.first_name}} {% endif %}{{context_user.email}}
        </a>
        <ul class="dropdown-menu">
          <li><a class="dropdown-item" href="{% url 'users:profile' %}">Профиль</a></li>
          <li><a class="dropdown-item" href="{% url 'users:logout' %}">Выйти</a></li>
        </ul>
      </div>
    </ul>
      {% else %}
      <div class="dropdown">
        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Авторизация
        </a>
        <ul class="dropdown-menu">
          <li><a class="dropdown-item" href="{% url 'users:login' %}">Вход</a></li>
          <li><a class="dropdown-item" href="{% url 'users:signup' %}">Регистрация</a></li>
        </ul>
      </div>
    </ul>
    {% endif %}
        </ul>
    </header>
</div>

intensive_django/templates/includes/item.html
{% load thumbnail %}
<div class="col-4">
    <div class="row">
        <div class="col-6">
            {% thumbnail item.mainimage.image "300x300" crop="center" as im %}
                <img src="{{ im.url }}"  class="img-fluid" alt="Картинки нет">
            {% endthumbnail %}
        </div>
    </div>
    <div class=row">

        <a class="fw-bold fs-3"
           href="{% url 'catalog:item_detail' pk=item.id %}">{{ item.name }}</a>
        <h4>Категория: {{ item.category.name }}</h4>
        <h5>Теги:
            {% for tag in item.tags.all %}
                {{ tag.name }}{% if not forloop.last %},{% endif %}
            {% endfor %}
        </h5>
        <h6>{{ item.text_rendered | safe | truncatewords:10 }}</h6>

    </div>
</div>

intensive_django/templates/includes/pagination.html
<nav aria-label="Page navigation example">
    <ul class="pagination">
        {% if page_obj.has_previous %}

            <li class="page-item"><a class="page-link" href="?page=1">&laquo; Первая</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Предыдущая</a></li>
        {% endif %}

        <li class="page-item disabled">
            <a class="page-link">Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</a>
        </li>

        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующая</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Последняя &raquo;</a></li>
        {% endif %}
    </ul>
</nav>