intensive_django/about/urls.py
from about import views
from django.urls import path

app_name = 'about'
urlpatterns = [
    path('', views.DescriptionView.as_view(), name='description'),
]

intensive_django/intensive_django/urls.py
import Core.views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('homepage.urls')),
    path('catalog/', include('catalog.urls')),
    path('about/', include('about.urls')),
    path('feedback/', include('feedback.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
]

handler404 = Core.views.NotFoundView.as_view()


if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

intensive_django/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path, reverse_lazy
from users.views import (ProfileView, SignUpFormView, UserDetailView,
                         UserListView)

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(
        template_name='users/login.html',
    ), name='login'),

    path('logout/', LogoutView.as_view(
        template_name='users/logout.html',
    ), name='logout'),

    path('password_change/', PasswordChangeView.as_view(
        template_name='users/password_change.html',
        success_url=reverse_lazy('users:password_change_done'),
    ), name='password_change'),

    path('password_change_done/', PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html',
    ), name='password_change_done'),

    path('password_reset/', PasswordResetView.as_view(
        template_name='users/password_reset.html',
        email_template_name='users/password_reset_email.html',
        success_url=reverse_lazy('users:password_reset_done'),
    ), name='password_reset'),

    path('password_reset_done/', PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html',
    ), name='password_reset_done'),

    path('password_reset_confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html',
             success_url=reverse_lazy('users:password_reset_complete'),
         ), name='password_reset_confirm'),

    path('password_reset_complete/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html',
    ), name='password_reset_complete'),

    path('signup/', SignUpFormView.as_view(), name='signup'),
    path('user_list/', UserListView.as_view(), name='user_list'),
    path(
        'user_detail/<int:pk>/',
        UserDetailView.as_view(),
        name='user_detail'
        ),
    path('profile/', ProfileView.as_view(), name='profile'),
]

intensive_django/users/models.py
from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager,
                                        PermissionsMixin)
from django.db import models
from django.utils import timezone
from users.validators import validate_birthday


class AccountManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **other_fields):

        if 'password1' in other_fields:
            password = other_fields.pop('password1')
        if 'password2' in other_fields:
            other_fields.pop('password2')

        email = self.normalize_email(email)
        user = self.model(
            email=email,
            **other_fields,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **other_fields):
        other_fields.setdefault('is_staff', False)
        other_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **other_fields)

    def create_superuser(self, email, password=None, **other_fields):
        other_fields['is_staff'] = True
        other_fields['is_superuser'] = True

        return self._create_user(email, password, **other_fields)


class Account(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    birthday = models.DateField(blank=True, null=True,
                                verbose_name='День рождения',
                                validators=[validate_birthday])

    first_name = models.CharField(max_length=50, blank=True, null=True,
                                  verbose_name='Имя')
    last_name = models.CharField(max_length=50, blank=True, null=True,
                                 verbose_name='Фамилия')

    # Django fields
    is_staff = models.BooleanField(default=False,
                                   verbose_name='Персонал сайта?')
    is_active = models.BooleanField(default=True,
                                    verbose_name='Активен?')
    date_joined = models.DateTimeField(default=timezone.now,
                                       verbose_name='Дата присоединения')
    last_login = models.DateTimeField(null=True,
                                      verbose_name='Последний вход')

    objects = AccountManager()

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'

    def get_full_name(self):
        return f'{self.first_name} {self.last_name}'

    def get_short_name(self):
        return self.first_name

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

intensive_django/users/forms.py
from django import forms
from users.models import Account


class SignUpForm(forms.ModelForm):
    password1 = forms.CharField(label='Пароль',
                                widget=forms.PasswordInput)
    password2 = forms.CharField(label='Подтверждение пароля',
                                widget=forms.PasswordInput)

    class Meta:
        model = Account
        fields = ('email',)

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Пароли не совпадают')
        return password2

    def save(self, **kwargs):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.save()

        return user


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ('first_name', 'last_name', 'birthday')

        widgets = {
            Account.birthday.field.name: forms.DateTimeInput(
                attrs={'type': 'date'}),
        }

intensive_django/users/views.py
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import DetailView, FormView, ListView
from users.forms import ProfileForm, SignUpForm
from users.models import Account


class SignUpFormView(FormView):
    template_name = 'users/signup.html'
    success_url = reverse_lazy('homepage:home')
    form_class = SignUpForm

    def form_valid(self, form):
        user = Account.objects.create_user(**form.cleaned_data)
        login(self.request, user)
        return super().form_valid(form)


class UserListView(ListView):
    template_name = 'users/user_list.html'
    model = Account

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['users'] = Account.objects.all().filter(
            is_active=True
            ).values('id', 'email', 'first_name')
        return context


class UserDetailView(DetailView):
    model = Account
    template_name = 'users/user_detail.html'


class ProfileView(LoginRequiredMixin, FormView):
    template_name = 'users/profile.html'
    success_url = reverse_lazy('users:profile')
    form_class = ProfileForm

    def form_valid(self, form):
        user = self.request.user
        user.first_name = form.cleaned_data['first_name']
        user.last_name = form.cleaned_data['last_name']
        user.birthday = form.cleaned_data['birthday']
        user.save()
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'instance': self.request.user})
        return kwargs

intensive_django/templates/users/login.html
{% extends 'base.html' %}

{% block title %}Вход{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="text-center fw-bolder">Вход</h1>
            </div>

            {% include 'includes/form.html' with form_method='post' button_name='Вход!' %}

        </div>

            <a href="{% url 'users:password_reset' %}" class="btn btn-outline-secondary " type="button">Смена пароля</a>
    </div>
{% endblock %}

intensive_django/templates/users/logout.html
{% extends 'base.html' %}

{% block title %}Вы вышли!{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="text-center fw-bolder">Ура! Вы наконец-то вышли!</h1>
            </div>

        </div>
    </div>
{% endblock %}

intensive_django/templates/users/password_change.html
{% extends 'base.html' %}

{% block title %}Смена пароля{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="text-center fw-bolder">Смена пароля</h1>
            </div>

            {% include 'includes/form.html' with form_method='post' button_name='Сменить пароль' %}

        </div>
    </div>
{% endblock %}

intensive_django/templates/users/password_change_done.html
{% extends 'base.html' %}

{% block title %}Вы сменили пароль!{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="text-center fw-bolder">Вы успешно сменили пароль!</h1>
            </div>

        </div>
    </div>
{% endblock %}

intensive_django/templates/users/password_reset.html
{% extends 'base.html' %}

{% block title %}Сброс пароля{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="text-center fw-bolder">Сброс пароля</h1>
            </div>

            {% include 'includes/form.html' with form_method='post' button_name='Сбросить' %}

        </div>
    </div>
{% endblock %}

intensive_django/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block title %}Восстановление пароля{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="text-center fw-bolder">Пароль успешно изменен</h1>
            </div>

        </div>
    </div>
{% endblock %}

intensive_django/templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block title %}Восстановление пароля{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">

            {% include 'includes/form.html' with form_method='post' button_name='Изменить' %}
            </div>

        </div>
    </div>
{% endblock %}

intensive_django/templates/users/password_reset_done.html
{% extends 'base.html' %}

{% block title %}Восстановление пароля{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="text-center fw-bolder">Письмо отправлено на почту!</h1>
            </div>

        </div>
    </div>
{% endblock %}

intensive_django/templates/users/password_reset_email.html
{% autoescape off %}

{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}

{% endautoescape %}

intensive_django/templates/users/profile.html
{% extends 'base.html' %}

{% block title %}Профиль{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="text-center fw-bolder">Профиль</h1>
            </div>

            {% include 'includes/form.html' with form_method='post' button_name='Изменить' %}

        </div>
            <a href="{% url 'users:password_change' %}" class="btn btn-outline-secondary " type="button">Смена пароля</a>
    </div>
{% endblock %}

intensive_django/templates/users/signup.html
{% extends 'base.html' %}

{% block title %}Регистрация{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="text-center fw-bolder">Регистрация</h1>
            </div>

            {% include 'includes/form.html' with form_method='post' button_name='Вперед!' %}

        </div>
    </div>
{% endblock %}

intensive_django/templates/users/user_detail.html
{% extends 'base.html' %}

{% block title %}Пользователь №{{account.id}}{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">

                <h3>{{ account.email }}</h3>
                <h4>{{ account.first_name }}
                    {{ account.last_name }}</h4>
                <h4>{{ account.birthday }}</h4>
            </div>

        </div>
    </div>
{% endblock %}

intensive_django/templates/users/user_list.html
{% extends 'base.html' %}

{% block title %}Список пользователей{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                {% for user in users %}
                    <a href="{% url 'users:user_detail' pk=user.id %}"><h3>{{ user.id }} - {{ user.email }}</h3></a>
                {% endfor %}
            </div>

        </div>
    </div>
{% endblock %}